; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
build_flags = 
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=1

; Fix for missing headers
lib_ldf_mode = deep+
lib_ignore = AsyncTCP_RP2040Wv

; --- OTA Configuration (Uncomment to use) ---
upload_protocol = espota
upload_port = 192.168.178.155 
upload_flags = --port=3232 

lib_deps = 
	https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA.git
	bitbank2/AnimatedGIF @ ^1.4.7
	mathieucarbou/ESPAsyncWebServer @ ^3.6.0
	mathieucarbou/AsyncTCP @ ^3.3.2
	bblanchon/ArduinoJson @ ^6.21.3
	adafruit/Adafruit BusIO@^1.17.4
	adafruit/Adafruit GFX Library@^1.12.4
	knolleary/PubSubClient @ ^2.8